spring:
  application:
    name: parking-webapp
  datasource:
    url: jdbc:sqlite:parking_webapp.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": false
  rabbitmq:
    host: ${MQ_HOST:localhost}
    port: ${MQ_PORT:5672}
    username: ${MQ_USER:guest}
    password: ${MQ_USER:guest}
    virtual-host: ${MQ_VHOST:/}
vaadin:
  launch-browser: true